version: '3.1'

services:
  nginx:
    build:
      context: /home/ubuntu/data/nginx-docker
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/data/nginx-docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - server

  web:
    build:
      context: /home/ubuntu/data/maplego/packages/web
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/data/maplego/packages/web:/usr/src/web

  server:
    build:
      context: /home/ubuntu/data/maplego/packages/server
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/data/maplego/packages/server:/usr/src/server
