version: '3.8'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /home/ubuntu/data/nginx-docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
      - server
    stdin_open: true
    tty: true

  web:
    build:
      context: /home/ubuntu/data/maplego/packages/web
    ports:
      - "3000:3000"
    volumes:
      - /home/ubuntu/data/maplego/packages/web:/usr/src/web
    stdin_open: true
    tty: true

  server:
    build:
      context: /home/ubuntu/data/maplego/packages/server
    ports:
      - "8080:8080"
    volumes:
      - /home/ubuntu/data/maplego/packages/server:/usr/src/server
    stdin_open: true
    tty: true
