import Providers from '@/components/common/system/Providers';
import type { Metadata } from 'next';
import { cookies } from 'next/headers';
import { ReactNode } from 'react';
import DesktopLayout from '@/components/desktop/layout/DesktopLayout';
import { fetchGetMe } from '@/lib/api/me';
import { fetchRefresh } from '@/lib/api/auth';
import Core from '@/components/common/base/Core';

export const metadata: Metadata = {
  title: '메이플고 - 메이플스토리 커뮤니티',
  description: 'Generated by create next app',
};

function getThemeInCookie() {
  const nextCookies = cookies();
  return nextCookies.get('theme')?.value;
}

async function getMyAccountWithRefresh() {
  const cookieStore = cookies();
  const refreshToken = cookieStore.get('refresh_token')?.value;
  const currentAccessToken = cookieStore.get('access_token')?.value;

  if (!currentAccessToken || !refreshToken) {
    return null;
  }

  const me = await fetchGetMe(currentAccessToken);
  // console.log(me);
  if (me?.payload?.isExpiredToken) {
    const { accessToken } = await fetchRefresh(refreshToken);
    // console.log(accessToken);
    // const me = await fetchGetMe(accessToken);
    // console.log(me);
    // return me;
  }

  return me;
}

export default async function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  const myAccount = await getMyAccountWithRefresh();
  const currentTheme = getThemeInCookie();
  return (
    <html
      lang="ko"
      className={currentTheme}
      style={{
        colorScheme: currentTheme,
      }}
    >
      <body>
        <Providers>
          <DesktopLayout theme={currentTheme}>{children}</DesktopLayout>
        </Providers>
      </body>
    </html>
  );
}
