import { Metadata } from 'next';
import MeDelete from '@/components/desktop/profile/meDelete/MeDelete';

export const metadata: Metadata = {
  title: '메이플고 - 회원탈퇴',
  description: 'Generated by create next app',
};

function MeDeletePage() {
  return <MeDelete />;
}

export default MeDeletePage;
